openapi: 3.0.1
info:
  title: ftps-app
  description: FTPS management.
  license:
    name: GPL-3.0-or-later
    url: https://www.gnu.org/licenses/gpl-3.0.fr.html
  version: 1.0.0
servers:
- url: http://waak.ddns.net/api
tags:
- name: account
- name: ftps_server
- name: auth
paths:
  /account:
    get:
      tags:
      - account
      summary: Get all accounts
      operationId: "getAccounts"
      responses:
        200:
          description: successful operation
          content: {}
        500:
          description: internal server error
          content: {}
    post:
      tags:
      - account
      summary: Create account
      operationId: "createAccount"
      requestBody:
        description: Account object to create
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      responses:
        201:
          description: successful operation
          content: {}
        500:
          description: internal server error
          content: {}
      x-codegen-request-body-name: account
    delete:
      tags:
      - account
      summary: Delete all accounts
      operationId: "deleteAccounts"
      responses:
        200:
          description: successful operation
          content: {}
        500:
          description: internal server error
          content: {}
  /account/{accountId}:
    get:
      tags:
      - account
      summary: Get account by account ID
      operationId: "getAccount"
      parameters:
      - name: accountId
        in: path
        description: ID of account to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content: {}
        500:
          description: internal server error
          content: {}
    delete:
      tags:
      - account
      summary: Delete account
      operationId: "deleteAccount"
      parameters:
      - name: accountId
        in: path
        description: ID of account to delete
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: succesful operation
          content: {}
        500:
          description: internal server error
          content: {}
  /ftps_server:
    get:
      tags:
      - ftps_server
      summary: Get all FTPS servers
      operationId: "getFtpsServers"
      responses:
        200:
          description: successful operation
          content: {}
        500:
          description: internal server error
          content: {}
    post:
      tags:
      - ftps_server
      summary: Create FTPS server
      operationId: "createFtpsServer"
      requestBody:
        description: FTPS Server object to create
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/FtpsServer'
        required: true
      responses:
        201:
          description: successful operation
          content: {}
        500:
          description: internal server error
          content: {}
      x-codegen-request-body-name: FtpsServer
    delete:
      tags:
      - ftps_server
      summary: Delete all FTPS servers
      operationId: "deleteFtpsServers"
      responses:
        200:
          description: successful operation
          content: {}
        500:
          description: internal server error
          content: {}
  /ftps_server/{serverId}:
    get:
      tags:
      - ftps_server
      summary: Get FTPS server by server ID
      operationId: "getFtpsServer"
      parameters:
      - name: serverId
        in: path
        description: ID of FTPS server to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content: {}
        500:
          description: internal server error
          content: {}
    delete:
      tags:
      - ftps_server
      summary: Delete FTPS server
      operationId: "deleteFtpsServer"
      parameters:
      - name: serverId
        in: path
        description: ID of FTPS server to delete
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: succesful operation
          content: {}
        500:
          description: internal server error
          content: {}
  /auth/login:
    post:
      tags:
      - auth
      summary: Login
      operationId: ""
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - accountHash
              - accountName
              properties:
                accountName:
                  type: string
                  description: account name
                accountHash:
                  type: string
                  description: account hashed password
        required: true
      responses:
        200:
          description: successful operation
          content: {}
        500:
          description: internal server error
          content: {}
  /auth/logout:
    post:
      tags:
      - auth
      summary: Logout
      operationId: ""
      requestBody:
        description: ID of the account to logout
        content:
          '*/*':
            schema:
              type: string
        required: true
      responses:
        200:
          description: successful operation
          content: {}
        500:
          description: internal server error
          content: {}
      x-codegen-request-body-name: accountId
components:
  schemas:
    Account:
      type: object
      properties:
        _id:
          type: integer
          format: int64
        accountName:
          type: string
        hash:
          type: string
        servers:
          type: array
          items:
            $ref: '#/components/schemas/FtpsServer'
    FtpsServer:
      type: object
      properties:
        _id:
          type: integer
          format: int64
        host:
          type: string
        port:
          type: integer
          format: int64
        user:
          type: string
        password:
          type: string
        certificate_path:
          type: string        
        account:
          $ref: '#/components/schemas/Account'
